version: '3'
services:
  api:
    hostname: api
    build:
      context: ..
      dockerfile: dissertation/api/Dockerfile
    image: api
    ports:
      - 8888:8888
    depends_on:
      - messaging
      - database
  client:
    hostname: client
    build:
      context: ..
      dockerfile: dissertation/client/Dockerfile
    image: client
    ports:
      - 8080:8080
    depends_on:
      - database
  store:
    hostname: store
    build:
      context: ..
      dockerfile: dissertation/store/Dockerfile
    image: store
    depends_on:
      - messaging
      - database
  review:
    hostname: review
    build:
      context: ..
      dockerfile: dissertation/review/Dockerfile
    image: review
    depends_on:
      - messaging
      - database
  update:
    hostname: update
    build:
      context: ..
      dockerfile: dissertation/update/Dockerfile
    image: update
    depends_on:
      - messaging
      - database
  messaging:
    build:
      context: .
      dockerfile: messaging
    image: messaging
    hostname: messaging
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671
  database:
    build:
      context: .
      dockerfile: database
    image: database
    hostname: database
    tty: true
    volumes:
     - /mnt/dissertation:/opt/couchbase/var
    ports:
     - 8091:8091
     - 8092:8092
     - 8093:8093
     - 11210:11210